[package]
name = "openmls"
version = "0.4.1"
authors = ["OpenMLS Authors"]
edition = "2021"
description = "This is a WIP Rust implementation of the Messaging Layer Security (MLS) protocol based on draft 12+."
license = "MIT"
documentation = "https://openmls.github.io/openmls/"
repository = "https://github.com/openmls/openmls/"
readme = "../README.md"

[dependencies]
openmls_traits = { workspace = true }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
log = { version = "0.4", features = ["std"] }
tls_codec = { workspace = true }
rayon = "^1.5.0"
thiserror = "^1.0"
backtrace = "0.3"

[features]
default = []
crypto-subtle = [] # Enable subtle crypto APIs that have to be used with care.
test-utils = []
evercrypt = []     # Evercrypt needs to be enabled individually (testing only)
crypto-debug = []  # ☣️ Enable logging of sensitive cryptographic information
content-debug = [] # ☣️ Enable logging of sensitive message content

[dev-dependencies]
rstest = { version = "0.16" }
rstest_reuse = { version = "0.4" }
rand = { version = "0.8" }
openmls_rust_crypto = { version = "0.1.0", path = "../openmls_rust_crypto" }
openmls_evercrypt = { version = "0.1.0", path = "../evercrypt_backend" }
openmls_basic_credential = { version = "0.1.0", path = "../basic_credential", features = [
    "cloneable",
    "test-utils",
] }
backtrace = "0.3"
criterion = "^0.4"
hex = { version = "0.4", features = ["serde"] }
itertools = "0.10"
lazy_static = "1.4"
openmls = { path = ".", features = ["test-utils"] }
pretty_env_logger = "0.4"
tempfile = "3"

# x64 targets get evercrypt compiled into dev-dependencies.
[target.'cfg(target_arch = "x86_64")'.dev-dependencies.openmls]
path = "."
features = ["test-utils", "evercrypt"]

[[bench]]
name = "benchmark"
harness = false
