[package]
name = "openmls"
version = "0.4.1"
authors = ["OpenMLS Authors"]
edition = "2021"
description = "This is a WIP Rust implementation of the Messaging Layer Security (MLS) protocol based on draft 12+."
license = "MIT"
documentation = "https://openmls.github.io/openmls/"
repository = "https://github.com/openmls/openmls/"
readme = "../README.md"

[dependencies]
openmls_traits = { version = "0.1.0", path = "../traits" }
serde = { version = "^1.0", features = ["derive"] }
log = { workspace = true }
tls_codec = { workspace = true }
rayon = "^1.5.0"
thiserror = { workspace = true }
backtrace = "0.3"
# Only required for tests.
rand = { version = "0.8", optional = true }
serde_json = { version = "1.0", optional = true }
# Crypto backends required for KAT and testing - "test-utils" feature
itertools = { version = "0.10", optional = true }
openmls_rust_crypto = { version = "0.1.0", path = "../openmls_rust_crypto", optional = true }
openmls_libcrux = { version = "0.1.0", path = "../libcrux_backend", optional = true }
openmls_basic_credential = { version = "0.1.0", path = "../basic_credential", optional = true, features = ["clonable", "test-utils"] }
rstest = { version = "^0.16", optional = true }
rstest_reuse = { version = "0.4", optional = true }

[features]
default = []
crypto-subtle = [] # Enable subtle crypto APIs that have to be used with care.
test-utils = [
    "dep:serde_json",
    "dep:itertools",
    "dep:openmls_rust_crypto",
    "dep:rand",
    "dep:rstest",
    "dep:rstest_reuse",
    "dep:openmls_basic_credential",
    "dep:openmls_libcrux",
]
crypto-debug = [] # ☣️ Enable logging of sensitive cryptographic information
content-debug = [] # ☣️ Enable logging of sensitive message content

[dev-dependencies]
backtrace = "0.3"

criterion = "^0.4"
hex = { version = "0.4", features = ["serde"] }
itertools = "0.10"
lazy_static = "1.4"
openmls = { path = ".", features = ["test-utils"] }
pretty_env_logger = "0.4"
rstest = "^0.16"
rstest_reuse = "0.4"
tempfile = "3"
openmls_test = { path = "../openmls_test" }

[[bench]]
name = "benchmark"
harness = false
