[workspace]
members = [
    "openmls",
    "traits",
    "openmls_rust_crypto",
    "fuzz",
    "cli",
    "interop_client",
    "memory_keystore",
    "libcrux_backend",
    "delivery-service/ds",
    "delivery-service/ds-lib",
    "basic_credential"
]
resolver = "2"

# Patching unreleased crates
[workspace.dependencies]
tls_codec = { version = "0.3.0-pre.2", features = ["derive", "serde", "mls"] }
log = { version = "0.4", features = ["std"] }
thiserror = "1.0"

[patch.crates-io.hpke-rs]
git = "https://github.com/franziskuskiefer/hpke-rs.git"

[patch.crates-io.hpke-rs-crypto]
git = "https://github.com/franziskuskiefer/hpke-rs.git"

[patch.crates-io.libcrux]
path = "../libcrux"

[patch.crates-io]
hacl = { path = "../hacl-packages/rust" }
